# Generated by Django 4.1.7 on 2023-03-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200)),
                ('store_location', models.CharField(max_length=200)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
