# Generated by Django 4.1.7 on 2023-03-15 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icecream', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='store_name',
            new_name='name',
        ),
    ]
