# Generated by Django 4.1.7 on 2023-03-15 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icecream', '0002_rename_store_name_store_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='tub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(choices=[('VAN', 'Vanilla'), ('CHO', 'Chocolate'), ('STR', 'Strawberry'), ('MAT', 'Matcha'), ('COF', 'Coffee')], max_length=3)),
                ('size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_vegan', models.BooleanField()),
                ('is_gluten_free', models.BooleanField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tubs', to='icecream.store')),
            ],
        ),
    ]
