# Generated by Django 4.1.7 on 2023-03-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecream', '0003_tub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tub',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
