# Generated by Django 4.1.7 on 2023-03-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecream', '0004_alter_tub_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tub',
            name='flavor',
            field=models.CharField(choices=[('VANILLA', 'Vanilla'), ('CHOCOLATE', 'Chocolate'), ('STRAWBERRY', 'Strawberry'), ('MATCHA', 'Matcha'), ('COFFEE', 'Coffee')], max_length=15),
        ),
    ]
